# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: k8s-node-external-ip-watcher
    binary: k8s-node-external-ip-watcher
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: k8s-node-external-ip-watcher
    ids: [k8s-node-external-ip-watcher]
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: packages
    package_name: k8s-node-external-ip-watcher
    vendor: stone
    homepage: https://github.com/stone/k8s-node-external-ip-watcher
    maintainer: Fredrik Steen <fredrik@tty.se>
    description: |
      Kubernetes node external IP watcher
      Watches Kubernetes nodes for external IP changes and updates configuration files
    license: GPL-3.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

    contents:
      - src: tools/packaging/config.yaml
        dst: /etc/k8s-node-external-ip-watcher/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
      - src: tools/packaging/template.tmpl
        dst: /etc/k8s-node-external-ip-watcher/template.tmpl
        type: config|noreplace
        file_info:
          mode: 0644
      - src: tools/packaging/k8s-node-external-ip-watcher.service
        dst: /usr/lib/systemd/system/k8s-node-external-ip-watcher.service
        type: config|noreplace
        file_info:
          mode: 0644
      - src: README.md
        dst: /usr/share/doc/k8s-node-external-ip-watcher/README.md
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/k8s-node-external-ip-watcher/LICENSE
        file_info:
          mode: 0644
    scripts:
      postinstall: tools/packaging/postinstall.sh
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    rpm:
      group: System Environment/Daemons

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: stone
    name: k8s-node-external-ip-watcher
  draft: false
  prerelease: auto
  name_template: "{{.Version}}"
